### ISSUE TITLE
how to use this tool TLS attacker?

### ISSUE THREAD

**Issue by jameshentai** [RUB-NDS/TLS-Attacker#12]
I still don't understand how to use this tool. Give me example with my example ip is : 123.456.789. this ip vuln to tls-1.0, how to use tls attacker to hack this server? Show me all command i can use. thanks if someone answer, not for nothing. here is all i known, and this is real target:  http://imgur.com/a/BsbGk .

**Comment by jurajsomorovsky** [comment]
You have to provide the port, in your case most probably 443.
In that case it would be 123.456.789:443
