### ISSUE TITLE
Release to Maven Central?

### ISSUE THREAD

**Issue by thc202** [RUB-NDS/TLS-Attacker#18]
Are there any plans to release the artifacts to Maven Central? That would make it more straightforward to integrate the library in other projects.

**Comment by jurajsomorovsky** [comment]
Hmm, had no plans to do that, but it would be indeed helpful. I will try to handle this in the next days. Thanks for the pointer.

**Comment by thc202** [comment]
Thanks!

**Comment by ngoyal** [comment]
Any updates?  I still don't see it

**Comment by ic0ns** [comment]
We separated the ModifiableVariable Module and released it to Maven central. The rest of TLS-Attacker will probably follow soon with the release of TLS-Attacker 2.0.

**Comment by jurajsomorovsky** [comment]
ok it took us a bit longer than expected :)
https://mvnrepository.com/artifact/de.rub.nds.tlsattacker
