### ISSUE TITLE
Compilation fails on eclipse 

### ISSUE THREAD

**Issue by GianpaoloPedrazza** [RUB-NDS/TLS-Attacker#2]
There is a compilation issue on Eclipse (I'm using Luna Service Release 2 (4.4.2)) related with the pom.xml files. I'm getting the error message here below:
Plugin execution not covered by lifecycle configuration: com.googlecode.maven-java-formatter-plugin:maven-java-formatter-plugin:0.4:format (execution: default, phase: process-
sources)
I changed following pom files
Fuzzer/pom.xml
Runnable/pom.xml
TLS/pom.xml
Pom.xml
as described here
http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin
then anything worked fine for me. 
I have also seen a small bug in a java class.

**Comment by GianpaoloPedrazza** [comment]
[globdiff.txt](https://github.com/RUB-NDS/TLS-Attacker/files/258999/globdiff.txt)

**Comment by jurajsomorovsky** [comment]
Thank you!
