### ISSUE TITLE
Error: Not possible to use unrestricted policy in Oracle JDK..

### ISSUE THREAD

**Issue by H011YxW00D** [RUB-NDS/TLS-Attacker#21]
Getting the following when trying to run any version downloaded by .zip or .tar.gz:
Exception in thread "main" de.rub.nds.tlsattacker.tls.exceptions.ConfigurationException: Not possible to use unrestricted policy in Oracle JDK..
I tried installing the Java Cryptography Extension (JCE)Unlimited Strength Jurisdiction Policy Files in my ubuntu install thinking that would fix the problem but it didn't.

**Comment by jurajsomorovsky** [comment]
Hmm, Oracle modified some stuff in their crypto restriction policy handlers. Could you retry with the UnlimitedStrengthAgain branch?

```
git checkout UnlimitedStrengthAgain 
./mvnw clean package
```

If this does not work, set your default java version to OpenJDK...
```
set JAVA_HOME=/usr/lib/jvm ...
```
and then try again.
thanks
