### ISSUE TITLE
Problem detecting supported signature algorithms

### ISSUE THREAD

**Issue by randombit** [RUB-NDS/TLS-Attacker#26]
Using TLS-Attacker (and the BSI policy test script) I found a problem in Botan where even if SHA1 was disabled in the policy, we would negotiate it in the case that the client sends no `signature_algorithms` due to the implicit fallback hardcoded into the TLS v1.2 spec. (Thanks!)

But now that I've fixed it (in https://github.com/randombit/botan/pull/1173), the test is still failing and I am confused by the output:

```
ProtocolVersionTest
 Supported protocols: TLS12 
CryptoTest
 Supported cipher suites: 
  TLS12: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 
 Supported ciphers: AES_128_GCM, AES_128_CBC, AES_256_GCM, AES_256_CBC, 
 Supported key exchange algorithms: DHE_RSA, EC_DIFFIE_HELLMAN, 
 Supported MAC algorithms: HMAC_SHA384, AEAD, HMAC_SHA256, 
 Supported PRF algorithms: TLS_PRF_SHA256, TLS_PRF_SHA384, 
 Key sizes  (0 if not provided):
  Minimum RSA key size: 2048
  Minimum EC key size: 0
  Minimum DH group size: 2048
NamedCurvesTest
 Supported named curves: BRAINPOOLP256R1 SECP384R1 BRAINPOOLP512R1 BRAINPOOLP384R1 SECP256R1 
 Minimum ECDH group size: 256
SignatureAndHashAlgorithmsTest
 Supported signature and hash algorithms: RSA-SHA384 RSA-SHA256 RSA-SHA256 RSA-SHA384 
CipherSuiteOrderTest
 Server cipher suite selection cannot be recognized (lees than 2 cipher suites compatible)
19:12:24.577 [main] INFO  de.rub.nds.tlsattacker.testtls.policy.BotanPolicyParser - Currently cannot handle rule allow_dtls10
...
19:12:24.578 [main] ERROR de.rub.nds.tlsattacker.testtls.policy.TlsPeerProperties - The list of signature and hash algorithms is different from the configured signature and hash algorithms
\n\nPolicy tests failed. See the recent error and the server log output.
```

Several strange things here. First (and most important) it rejects the configuration, even though now we correctly reject all but the policy-allowed hashes. I wondered if perhaps this was because the Botan BSI policy also allows DSA+ECDSA, but the server only has an RSA key. But I tried editing the policy to only allow RSA and that didn't seem to have any effect. Second, RSA-SHA256 and RSA-SHA384 are repeated in the ` Supported signature and hash algorithms` line.  And thirdly it claims that "Server cipher suite selection cannot be recognized (lees than 2 cipher suites compatible)" after telling me 8 ciphersuites are supported.

**Comment by jurajsomorovsky** [comment]
I am sorry Jack, I completely missed this issue (worked on the internal repo for a longer time). I think you can safely ignore this. This appeared to be a bug in our code. We have now released a new TLS-Attacker version and are going to work on that one in the future.

I can still look into it. Can you tell me how to run the new tls_attacker script in botan? More precisely, what is the botan_ci_tools parameter to the script? 
Thanks

**Comment by randombit** [comment]
The idea is that points to a checkout of https://github.com/randombit/botan-ci-tools (the eventual goal of the script is to run the whole test suite as part of CI, so that repo includes a prebuild version of the TLS-Attacker jar).

It basically expects the following dir layout:

```
<specified dir>/TLS-Attacker
<specified dir>/TLS-Attacker/TLS-Attacker-1.2.jar
<specified dir>/TLS-Attacker/resources/testsuite
<specified dir>/TLS-Attacker/resources/fuzzing/workflows
```

So it almost (but does not quite) work to point it at a standard TLS-Attacker checkout. I think if you copied Runnable/target/TLS-Attacker-xxx.jar to the top level of the checkout directory, then passed the parent directory to run_tls_attacker.py, it would work.

This is kind of a mess, I should change the botan-ci-tools directory layout so it is equivalent to a standard TLS-Attacker checkout, and then have the script scan Runnable/target for anything matching TLS-Attacker-*.jar instead of hardcoding the version.

**Comment by jurajsomorovsky** [comment]
We just had a look on this and it seems that there are some bugs in the older TLS-Attacker 1.2 release. For example, the signature and hash algorithms were repeated because no hash values were computed for these enums in Java. I am sorry for the confusion.

We are currently developing a new TLS-Attacker version and do not support the older one anymore. We are also developing new tests and perform fuzzing, and give you more information once this is ready. Please do not invest your time currently to patch the TLS-Attacker scripts.

I hope this helps.

**Comment by randombit** [comment]
OK, thanks for letting me know. Looking forward to the new release.
