### ISSUE TITLE
Clean build is not possible. Missing dependencies for EAP. repo.nds.rub.de/repository/libs/ seems to be down

### ISSUE THREAD

**Issue by Dysnom** [RUB-NDS/TLS-Attacker#28]
When I attempt to build on a new system, the build fails at EAP with the following message:

[ERROR] Failed to execute goal on project EAP: Could not resolve dependencies for project de.rub.nds.tlsattacker:EAP:jar:1.2: Failure
to find org.jnetpcap:jnetpcap:jar:1.3.0 in https://repo.nds.rub.de/repository/libs/ was cached in the local repository, resolution will not be reattempted until the update interval of libs has elapsed or updates are forced -> [Help 1]

It looks like jnetpcap is not available because the https://repo.nds.rub.de/repository/libs/ directory is completely blank. Did a drive go down or something? This totally blocks anyone trying to use the project for the first time.
[EAP_Build_Log.txt](https://github.com/RUB-NDS/TLS-Attacker/files/1391437/EAP_Build_Log.txt)

**Comment by ic0ns** [comment]
Thanks for reporting, we are curently working on a fix.

**Comment by ngoyal** [comment]
fwiw this seems to build by replacing the org.jnetpcap dep w/ 

```
        <dependency>
            <groupId>jnetpcap</groupId>
            <artifactId>jnetpcap</artifactId>
            <version>1.4.r1425-1f</version>
        </dependency>
```

```
        <repository>
          <id>clojars</id>
          <url>https://clojars.org/repo/</url>
        </repository>
```
Needs to be added to the repositories in the main pom.xml though

**Comment by ic0ns** [comment]
We fixed the issue with our repository server. TLS-Attacker should build now again. Alternatively you can also use our current beta release.
