### ISSUE TITLE
ECDSA Curves in Client Certificate Verification

### ISSUE THREAD

**Issue by MatthiasHeuft** [RUB-NDS/TLS-Attacker#31]
During client verification in the CertificateVerifyMessagePreparator (see: https://github.com/RUB-NDS/TLS-Attacker/blob/d8aff453e5d0152541054d3d05b9a7dc83a7c98e/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/preparator/CertificateVerifyMessagePreparator.java#L69) the SignatureCalculator is used to generate a signature using the client's private key. During this process, the SignatureCalculator reads the private key from the config (see https://github.com/RUB-NDS/TLS-Attacker/blob/184e8c86490bdd2482442ebdf23b60bcf26de5a7/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/crypto/SignatureCalculator.java#L69). This key is constructed of the key bytes as well as the curve, which is also taken from config. No distinction is made between the curve for ECDHE and ECDSA. Shouldn't it be possible to select different curve for the key exchange and for the signature generation?

**Comment by ic0ns** [comment]
I guess you have a valid point. I'll put it on the todo list

**Comment by ic0ns** [comment]
As a side note: it seems client authentication is currently not really functional...

**Comment by MatthiasHeuft** [comment]
After I configured our test to use the same curve in ECDHE and in the ECDSA I was was able to connect to the test-server. However it did not check the validity of the certificate chain on the server side, but in general it seems to be functional.

**Comment by ic0ns** [comment]
I addressed your issue in TLS-Attacker version 2.3. Let me know if you experience further problems

**Comment by MatthiasHeuft** [comment]
Vielen Dank!

I found a minor error in the Config, which could be related to problems in the client authentication:

https://github.com/RUB-NDS/TLS-Attacker/blob/185abd490eea618f25c0cb874bd2a8b1d11bce8a/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/config/Config.java#L2104

The setter setDefaultClientSupportedCiphersuites is empty.

**Comment by ic0ns** [comment]
we fixed this in the upcoming version. Thanks for reporting!
