### ISSUE TITLE
Typo in help

### ISSUE THREAD

**Issue by msoosgds** [RUB-NDS/TLS-Attacker#34]
Hey! Awesome tool, loving it! Probably a typo here:

```
      Who to connect to. Syntax: localhost:4433
```

Probably it was meant to be 443? Cheers and thanks again for the tool!

**Comment by ic0ns** [comment]
openssl s_server uses port 4433 by default. Since we use TLS-Attacker mostly for our research with local servers we have 4433 there.  But you are right - for real world server 443 would be more appropriate.

**Comment by msoosgds** [comment]
Ahhh I see! Well, I understand now :) Closing :)
