### ISSUE TITLE
DHE Ciphersuites in Server-Mode

### ISSUE THREAD

**Issue by SidolFreiburg** [RUB-NDS/TLS-Attacker#38]
Hello!

We are running the TLS-Attacker as a server and we are using the DHE_RSA ciphersuites. When the attacker receives the Finished message, we get an error: "Could not decrypt Data with the provided parameters. Returning undecrypted data.". This is the case for GCM as for CBC ciphersuites. I attached a log file to this post. For the ECHDE ciphersuites, the same setup is working fine.

[TestClientConversation_DHE_RSA.txt](https://github.com/RUB-NDS/TLS-Attacker/files/1797771/TestClientConversation_DHE_RSA.txt)
[tls-attacker-dhe.txt](https://github.com/RUB-NDS/TLS-Attacker/files/1797772/tls-attacker-dhe.txt)

**Comment by ic0ns** [comment]
it looks like TLS-Attacker and the client you are testing against didn't compute the same Mastersecret. Do you have the possibility to debug the client? 
i could get the example server running with the ciphersuite eg:
`java -jar apps/TLS-Server.jar -port 4433 -cipher TLS_DHE_RSA_WITH_AES_128_CBC_SHA`

`./openssl s_client`

works for me. You are loading an other default config from "./resources/src/intern/default_config.xml" maybe there is a problem here? You example code does some strange things - but nothing I can see which should affect this specific problem.

**Comment by ic0ns** [comment]
You can try your code with mbed tls and high debug settings. It should print you the mastersecret and even the keyblock. This allows you to check if this part worked.

**Comment by SidolFreiburg** [comment]
You were right: We were using an outdated default_config.xml, from the attacker V2.3. It contained a parameter "defaultDhModulus", which is missing in the current default_config.xml. Maybe this caused the deviation. It works with the  current version.

Thank you for your help and sorry for bothering you!

**Comment by ic0ns** [comment]
Always happy to help :)
