### ISSUE TITLE
Does the invalid curve full test always throw an exception?

### ISSUE THREAD

**Issue by GianpaoloPedrazza** [RUB-NDS/TLS-Attacker#4]
Hi, I run the invalid curve full test using
java -jar TLS-Attacker-1.0.jar invalid_curve_full -connect $ip:$port
but I got following exception thrown

Exception in thread "main" java.lang.IllegalArgumentException: The Workflow does not contain any CLIENT_KEY_EXCHANGE
	at de.rub.nds.tlsattacker.tls.workflow.WorkflowTrace.getFirstHandshakeMessage(WorkflowTrace.java:204)
	at de.rub.nds.tlsattacker.attacks.ec.oracles.RealDirectMessageECOracle.executeValidWorkflowAndExtractCheckValues(RealDirectMessageECOracle.java:165)
	at de.rub.nds.tlsattacker.attacks.ec.oracles.RealDirectMessageECOracle.<init>(RealDirectMessageECOracle.java:70)
	at de.rub.nds.tlsattacker.attacks.impl.InvalidCurveAttackFull.executeAttack(InvalidCurveAttackFull.java:56)
	at de.rub.nds.tlsattacker.Main.main(Main.java:151)

I had a look at the parsed message and it contains a CLIENT_HELLO.

**Comment by jurajsomorovsky** [comment]
I am not sure what is happening there.
How have you triggered this bug? What server and server configurations have you used please? Is it possible to provide me with a wireshark trace?

After the worklow is, ECDHClientKeyExchangeMessage should be found. This has nothing to do with RSA client key exchange messages

**Comment by GianpaoloPedrazza** [comment]
Here is the full output of the run
~/TLS-Attacker/Runnable/target$ java -jar TLS-Attacker-1.0.jar invalid_curve_full -connect IP:443
09:31:51.343 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Using the following security providers
09:31:51.347 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SUN, version, 1.7
09:31:51.347 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunRsaSign, version, 1.7
09:31:51.347 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJSSE, version, 1.7
09:31:51.348 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJCE, version, 1.7
09:31:51.348 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJGSS, version, 1.7
09:31:51.348 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunSASL, version, 1.7
09:31:51.348 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider XMLDSig, version, 1.0
09:31:51.349 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunPCSC, version, 1.7
09:31:51.349 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider BC, version, 1.54
09:31:51.360 [main] INFO  de.rub.nds.tlsattacker.attacks.impl.InvalidCurveAttackFull - Executing attack against the server with named curve SECP256R1
09:31:51.463 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - Preparing the following protocol message to send: class de.rub.nds.tlsattacker.tls.protocol.handshake.ClientHelloMessage
09:31:51.477 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor -
CLIENT_HELLO
  Handshake Message Length: 95
  Protocol Version: TLS12
  Client Unix Time: Fri May 13 09:31:51 CEST 2016
  Client Random:
  CC F8 31 D6 64 10 3A 0E  EC 44 66 05 1B A2 BD 51
  26 73 E6 64 85 F6 7A 16  4A 32 B5 7F
  Session ID:
  Supported Cipher Suites: C0 0E C0 04
  Supported Compression Methods: 00
  Extensions:
09:31:51.479 [main] DEBUG de.rub.nds.tlsattacker.tls.record.RecordHandler - The protocol message(s) was split into 1 record(s).
09:31:51.493 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - Records going to be sent:
  16 03 03 00 63 01 00 00  5F 03 03 57 35 82 E7 CC
  F8 31 D6 64 10 3A 0E EC  44 66 05 1B A2 BD 51 26
  73 E6 64 85 F6 7A 16 4A  32 B5 7F 00 00 04 C0 0E
  C0 04 01 00 00 32 00 0A  00 04 00 02 00 17 00 0B
  00 02 01 00 00 0D 00 20  00 1E 06 01 06 02 06 03
  05 01 05 02 05 03 04 01  04 02 04 03 03 01 03 02
  03 03 02 01 02 02 02 03
09:31:51.508 [main] DEBUG de.rub.nds.tlsattacker.transport.SimpleTransportHandler - Accepted 7 new bytes from server
09:31:51.511 [main] DEBUG de.rub.nds.tlsattacker.transport.SimpleTransportHandler - 15 03 03 00 02 02 28
09:31:51.512 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - HandshakeStatus default
09:31:51.513 [main] DEBUG de.rub.nds.tlsattacker.tls.record.RecordHandler - Raw protocol bytes from the current record:  02 28
09:31:51.514 [main] DEBUG de.rub.nds.tlsattacker.tls.record.RecordHandler - The protocol message(s) were collected from 1 record(s).
09:31:51.515 [main] DEBUG de.rub.nds.tlsattacker.tls.constants.ProtocolMessageType - Trying to get a protocol message handler for the following content type: ALERT
09:31:51.518 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - The configured protocol message is not equal to the message being parsed or the message was not found.
09:31:51.521 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - The following message was parsed:
ALERT message:
  Level: FATAL
  Description: HANDSHAKE_FAILURE
09:31:51.521 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - The workflow execution is stopped because of a FATAL error
Exception in thread "main" java.lang.IllegalArgumentException: The Workflow does not contain any CLIENT_KEY_EXCHANGE
        at de.rub.nds.tlsattacker.tls.workflow.WorkflowTrace.getFirstHandshakeMessage(WorkflowTrace.java:204)
        at de.rub.nds.tlsattacker.attacks.ec.oracles.RealDirectMessageECOracle.executeValidWorkflowAndExtractCheckValues(RealDirectMessageECOracle.java:165)
        at de.rub.nds.tlsattacker.attacks.ec.oracles.RealDirectMessageECOracle.<init>(RealDirectMessageECOracle.java:70)
        at de.rub.nds.tlsattacker.attacks.impl.InvalidCurveAttackFull.executeAttack(InvalidCurveAttackFull.java:56)
        at de.rub.nds.tlsattacker.Main.main(Main.java:151)

**Comment by GianpaoloPedrazza** [comment]
On server side there is an instance of nginx configured like described on https://weakdh.org/sysadmin.html
except for the ciphers (I have HIGH:!aECDH:!ADH:!3DES:!MD5:!DSS:!RC4:!EXP:!eNULL:!NULL:!aNULL instead)

**Comment by GianpaoloPedrazza** [comment]
I started a tcpdump an this pointed out that the server replied with an handshake failure message to the initial Client Hello request. I run "openssl ecparam -list_curves" on the server and SECP256R1 was not included in the list. So I guess that's it. It is simple unsupported.

**Comment by GianpaoloPedrazza** [comment]
![invalid_curve_full_handshake_failure](https://cloud.githubusercontent.com/assets/8958003/15257506/e415f5fa-1946-11e6-83ce-49b8a50db992.png)

**Comment by GianpaoloPedrazza** [comment]
After a long monologue, at the end of the day I think finally I have got it.
invalid_curve 
Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA 
Cipher Suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
are both supported ciphers

invalid_curve_full 
Cipher Suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA 
Cipher Suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA 
are both NOT supported ciphers

**Comment by jurajsomorovsky** [comment]
This is indeed confusing. I changed this in my developer version so that all 4 cipher suites are supported in both tests by default and will push with the new version soon.

Thank you!
