### ISSUE TITLE
Won't work with Java 9

### ISSUE THREAD

**Issue by strangeloveBsc** [RUB-NDS/TLS-Attacker#40]
Hi, 
so I wanted to try out this tool of yours (more specific: the TLS-Scanner module) and while it compiles just fine (Scanner throws error in some tests, but that's another issue) it won't run on my machine:

`
<user>@<host>:~/tools/TLS-Attacker$ java -jar apps/Attacks.jar padding_oracle -connect localhost:443 
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXB
	at de.rub.nds.tlsattacker.core.config.ConfigIO.read(ConfigIO.java:42)
	at de.rub.nds.tlsattacker.core.config.Config.createConfig(Config.java:78)
	at de.rub.nds.tlsattacker.core.config.TLSDelegateConfig.createConfig(TLSDelegateConfig.java:71)
	at de.rub.nds.tlsattacker.attacks.config.PaddingOracleCommandConfig.createConfig(PaddingOracleCommandConfig.java:67)
	at de.rub.nds.tlsattacker.attacks.impl.PaddingOracleAttacker.<init>(PaddingOracleAttacker.java:55)
	at de.rub.nds.tlsattacker.attacks.Main.main(Main.java:126)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXB
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 6 more
`

Which according to [Stackoverflow](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) this issue is based on the latest Java-Version (Java 9). Which matches my observation:
`
java --version
openjdk 9.0.4
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)
`

**Edits: Readability**

**Comment by ic0ns** [comment]
Hey strangeloveBsc,
I personally did not try java 9 yet (since it is still very fresh) and probably some of our dependencys are very likely not compatible with it yet. I recommend Java 8. We are currently not trying to move to Java 9 in the near future.
cheers
robert

**Comment by strangeloveBsc** [comment]
Hi Robert, 
thank you for your quick reply. If you don't mind I'll leave this open (unless you're graded / paid for being issue-free) so I know when to try again and not being misleading about this "issue" being solved.

Best Regards

Mike

**Comment by ic0ns** [comment]
sure :)

**Comment by fxa** [comment]
After some hours playing with TLS-Attacker, maven and java 12 I finally got it to work by adding the following dependencies to the pom.
Hope that helps
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.2</version>
</dependency>

<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.2</version>
</dependency>

**Comment by ApolloLV** [comment]
I ran into this issue today and was not able to resolve it without downgrading to java 8.
@fxa I tried variations of the jakarta xml fix, but that only moved the issues from compile time to run time.

**Comment by fxa** [comment]
Hello @ApolloLV  
for me that worked. compile time and run time.
I am using java version "12.0.2" 2019-07-16
and mvn 3.3.9.
I only changed the pom, that is my git diff:
-        <repository>
-            <id>ossrh</id>
-            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
-        </repository>
+
+<repository>
+    <id>central</id>
+    <url>http://repo.maven.apache.org/maven2/</url>
+</repository>
+
...
         </dependency>
+
+
+<dependency>
+    <groupId>jakarta.xml.bind</groupId>
+    <artifactId>jakarta.xml.bind-api</artifactId>
+    <version>2.3.2</version>
+</dependency>
+
+
+<dependency>
+    <groupId>org.glassfish.jaxb</groupId>
+    <artifactId>jaxb-runtime</artifactId>
+    <version>2.3.2</version>
+</dependency>
+
+
     </dependencies>
...
         <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
-        <maven.compiler.source>1.7</maven.compiler.source>
-        <maven.compiler.target>1.7</maven.compiler.target>
+        <maven.compiler.source>1.8</maven.compiler.source>
+        <maven.compiler.target>1.8</maven.compiler.target>
         <licenseOwner>Ruhr University Bochum, Hackmanit GmbH</licenseOwner>

**Comment by fxa** [comment]
@ApolloLV for me that worked compile time and runtime
I changed the pom to (could not attach, because xml is not supported here):
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>de.rub.nds.tlsattacker</groupId>
    <artifactId>TLS-Attacker</artifactId>
    <version>3.3.1</version>
    <packaging>pom</packaging>
    <inceptionYear>2015</inceptionYear>
    <name>TLS-Attacker</name>
    <url>https://github.com/RUB-NDS/TLS-Attacker</url>
    <description>TLS-Attacker is a Java-based framework for analyzing TLS libraries. It is developed by the Ruhr University Bochum (http://nds.rub.de/) and the Hackmanit GmbH (http://hackmanit.de/). </description>
    
    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    
    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>

<repository>
    <id>central</id>
    <url>http://repo.maven.apache.org/maven2/</url>
</repository>

    </distributionManagement>
    
    
    <scm>
        <connection>scm:git:git://github.com/RUB-NDS/TLS-Attacker.git</connection>
        <developerConnection>scm:git:ssh://github.com/RUB-NDS/TLS-Attacker.git</developerConnection>
        <url>https://github.com/RUB-NDS/TLS-Attacker/tree/master</url>
    </scm>
    
    <developers>
        <developer>
            <id>jsomorovsky</id>
            <name>Juraj Somorovsky</name>
            <email>Juraj.Somorovsky@rub.de</email>
            <url>http://www.nds.rub.de/</url>
            <organization>NDS</organization>
            <organizationUrl>http://www.nds.rub.de</organizationUrl>
            <roles>
                <role>Architect</role>
                <role>Developer</role>
            </roles>
        </developer>
        <developer>
            <id>ic0ns</id>
            <name>Robert Merget</name>
            <email>robert.merget@rub.de</email>
            <url>http://www.nds.rub.de/</url>
            <organization>NDS</organization>
            <organizationUrl>http://www.nds.rub.de</organizationUrl>
            <roles>
                <role>Developer</role>
            </roles>
        </developer>
    </developers>
    <modules>
        <module>Utils</module>
        <module>Transport</module>
        <module>TLS-Core</module>
        <module>TLS-Client</module>
        <module>TLS-Server</module>
        <module>TLS-Mitm</module>
        <module>Attacks</module>
        <module>TLS-Forensics</module>
        <module>TraceTool</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
            <version>1.69</version>
        </dependency>
        <dependency>
            <groupId>org.jmockit</groupId>
            <artifactId>jmockit</artifactId>
            <version>1.34</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-all</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.60</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-debug-jdk15on</artifactId>
            <version>1.60</version>
        </dependency>
        <dependency>
            <groupId>com.openpojo</groupId>
            <artifactId>openpojo</artifactId>
            <version>0.8.6</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.ow2.asm</groupId>
            <artifactId>asm</artifactId>
            <version>5.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
        </dependency>
        <dependency>
            <groupId>de.rub.nds</groupId>
            <artifactId>ModifiableVariable</artifactId>
            <version>2.5</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.10</version>
        </dependency>
        <dependency>
            <groupId>org.cryptomator</groupId>
            <artifactId>siv-mode</artifactId>
            <version>1.3.1</version>
        </dependency>


<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.2</version>
</dependency>


<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.2</version>
</dependency>


    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                        <execution>             
                            <id>copy</id>
                            <phase>package</phase>
                            <goals>
                                <goal>copy</goal>
                            </goals>
                            <configuration>
                                <artifactItems>
                                    <artifactItem>
                                        <groupId>${project.groupId}</groupId>
                                        <artifactId>${project.artifactId}</artifactId>
                                        <version>${project.version}</version>
                                        <type>${project.packaging}</type>
                                        <destFileName>${project.build.finalName}.${project.packaging}</destFileName>
                                    </artifactItem>
                                </artifactItems>
                                <outputDirectory>${project.parent.basedir}/apps</outputDirectory>
                            </configuration>
                        </execution>
                        <execution>
                            <id>copy-dependencies</id>
                            <phase>package</phase> 
                            <goals> 
                                <goal>copy-dependencies</goal> 
                            </goals> 
                            <configuration> 
                                <outputDirectory>${project.parent.basedir}/apps/lib</outputDirectory>
                                
                                <includeScope>compile</includeScope> 
                            </configuration> 
                        </execution> 
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.20.1</version>
                    <configuration>
                        <trimStackTrace>false</trimStackTrace>
                        <includes>
                            <include>**/*.java</include>
                        </includes>
                        
                        <excludedGroups>de.rub.nds.tlsattacker.util.tests.SlowTests,de.rub.nds.tlsattacker.util.tests.IntegrationTests</excludedGroups>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>2.20.1</version>
                    <configuration>
                        
                        <excludes>
                            <exclude>**/*.java</exclude>
                        </excludes>
                        
                        <groups>${includegroups}</groups>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.7.0</version>
                    <configuration>
                        <source>1.7</source>
                        <target>1.7</target>
                    </configuration>
                </plugin>
                
                <plugin>
                    <groupId>net.revelc.code</groupId>
                    <artifactId>formatter-maven-plugin</artifactId>
                    <version>0.5.2</version>
                </plugin>
                
                <plugin>
                    <groupId>com.mycila</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>3.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>2.9</version>
                </plugin>
            </plugins>
        </pluginManagement> 
        <plugins>
            <plugin>
                <groupId>net.revelc.code</groupId>
                <artifactId>formatter-maven-plugin</artifactId>
                <configuration>
                    <configFile>${main.basedir}/maven-eclipse-codestyle.xml</configFile>
                    <lineEnding>LF</lineEnding>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <configuration>
                    <header>${main.basedir}/license_header_plain.txt</header>
                    <strictCheck>true</strictCheck>
                    <includes>
                        <include>src/**/*.java</include>
                    </includes>
                    <properties>
                        <year>${project.inceptionYear}</year>
                        <owner>Ruhr University Bochum, Hackmanit GmbH</owner>
                    </properties>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.4</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <phase>deploy</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <additionalparam>-Xdoclint:none</additionalparam>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <skip>${skip.signature}</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.8</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    
                    <autoReleaseAfterClose>false</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.5</version>
                <configuration>
                    <effort>Max</effort>
                    <threshold>Low</threshold>
                    <xmlOutput>true</xmlOutput>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
                <configuration>
                    <configLocation>${main.basedir}/checkstyle.xml</configLocation>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>3.8</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jxr-plugin</artifactId>
                <version>2.5</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.4</version>
                <configuration>
                    <additionalparam>-Xdoclint:none</additionalparam>
                </configuration>
            </plugin>
        </plugins>
    </reporting>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <licenseOwner>Ruhr University Bochum, Hackmanit GmbH</licenseOwner>
        <main.basedir>${project.basedir}</main.basedir>
        
        <skip.signature>true</skip.signature>
    </properties>
</project>
`

**Comment by jurajsomorovsky** [comment]
should be fixed with the newest versions, it now supports java 11
