### ISSUE TITLE
error in TLS_DHE_RSA_WITH_AES_128_CBC_SHA 

### ISSUE THREAD

**Issue by merc1995** [RUB-NDS/TLS-Attacker#41]
hello,when I use`java -jar Tracetool.jar -running_mode CLIENT -cipher TLS_DHE_RSA_WITH_AES_128_CBC_SHA -workflow_trace_type FULL -workflow_output out.xml` to construct a xml,I get the out.xml as follow:
```xml
<workflowTrace>
    <Send>
        <messages>
            <ClientHello>
                <extensions>
                    <ECPointFormat/>
                    <EllipticCurves/>
                    <SignatureAndHashAlgorithmsExtension/>
                    <RenegotiationInfoExtension/>
                </extensions>
            </ClientHello>
        </messages>
    </Send>
    <Receive>
        <expectedMessages>
            <ServerHello>
                <extensions>
                    <ECPointFormat/>
                    <RenegotiationInfoExtension/>
                </extensions>
            </ServerHello>
            <Certificate/>
            <DHEServerKeyExchange/>
            <ServerHelloDone/>
        </expectedMessages>
    </Receive>
    <Send>
        <messages>
            <DHClientKeyExchange/>
            <ChangeCipherSpec/>
            <Finished/>
        </messages>
    </Send>
    <Receive>
        <expectedMessages>
            <ChangeCipherSpec/>
            <Finished/>
        </expectedMessages>
    </Receive>
    <Send>
        <messages>
            <Application/>
        </messages>
    </Send>
</workflowTrace>
```
Then,I start the TLS server on my 4433 port,use `java -jar TLS-Client.jar -connect localhost:4433 -workflow_input out.xml`,but I get the AlertMessage:
```
09:00:06.136 [main] INFO  core.workflow.WorkflowExecutor - Connecting to localhost:4433
09:00:06.149 [main] INFO  core.workflow.action.TlsAction - Sending messages (client): CLIENT_HELLO,
09:00:07.320 [main] INFO  core.workflow.action.TlsAction - Received Messages (client): SERVER_HELLO, CERTIFICATE, SERVER_HELLO_DONE,
09:00:07.320 [main] INFO  core.workflow.action.TlsAction - Sending messages (client): DH_CLIENT_KEY_EXCHANGE, CHANGE_CIPHER_SPEC, FINISHED,
09:00:07.392 [main] INFO  core.workflow.action.TlsAction - Received Messages (client): AlertMessage:
  Level: AlertLevel{value=FATAL}
  Description: AlertDescription{value=DECRYPT_ERROR},
09:00:07.392 [main] INFO  core.workflow.action.TlsAction - Sending messages (client): APPLICATION,
```
It seems that the Server didn't send a DH_SERVER_KEY_EXCHANGE.
Is there any problems,or I just misuse it ?thx.

**Comment by ic0ns** [comment]
The Problem seems to be that your Server is not selecting the Ciphersuite you hoped he select. He probably selected an RSA Ciphersuite. 
The WorkflowTrace itself does not contain Information about your preferred Ciphersuite. If you want to tell TLS-Attacker to only use a specific Ciphersuite in its Clienthello (in your case TLS_DHE_RSA_WITH_AES_128_CBC_SHA) you have to start the TLS-Client also with the -cipher TLS_DHE_RSA_WITH_AES_128_CBC_SHA flag (or an appropriate config.xml). Otherwise TLS-Attacker will send a default list of Ciphersuites in its ClientHelloMessage and then proceed to send a DHE ClientKeyExchange Message to whatever Ciphersuite the Server selected, which most of the time is probably not what you want it to do.
Cheers
ic0ns

**Comment by merc1995** [comment]
thx!
I also started the TLS-Client with -cipher TLS_DHE_RSA_WITH_AES_128_CBC_SHA ,and I modify the DHClientKeyExchange in xml,just like this:
```xml
<DHClientKeyExchange>
<y>
		<bigIntegerShiftLeftModification>
		<shift>
		41
		</shift>
		</bigIntegerShiftLeftModification>
</y> 
<DHClientKeyExchange>
```
but it seems that the value do not change ,,, could you help me.

**Comment by ic0ns** [comment]
But you see the DHServerKeyExchangeMessage now?

**Comment by merc1995** [comment]
oops,I didn't see that.I'll check it out,thank you.

**Comment by ic0ns** [comment]
Regarding your modification:

If you want to modify the DHClientKeyExchangeMessage you will probably have to look into the source code of the DHClientKeyExchangeMessage to get the syntax right, or alternativly create a workflow yourself by running TLS-Client.jar with the `-workflow_output` flag. This should create a workflow with values which should show you the exact syntax on how to modify specific values.

**Comment by ic0ns** [comment]
Can i close this issue or are you still experiencing issues?
