### ISSUE TITLE
Question about the fuzzing stage phase1

### ISSUE THREAD

**Issue by Krace** [RUB-NDS/TLS-Attacker#42]
Hello,I've read your paper `Systematic Fuzzing and Testing of TLS Libraries`,It's very amazing and I've learned a lot from it.
Here I still have one question.In the fuzzing stage phase1,other than the balcklist, how could you determinate which variables influence the correct protocol flow.
My thanks to you :P

**Comment by jurajsomorovsky** [comment]
Hi, thank you for your interest in our research.
In phase 1, as far as I remember, for each variable, we executed 100 random modifications in a valid protocol flow. If none of these modifications influenced the tested variable, we assumed that the variable modification was not relevant for the protocol flow.
Example: TLS protocol messages contain nested structures of length variables, e.g.:
04 03 xx yy zz
(where the first variable defines the length of the whole structure and the second length variable defines the length of xxyyzz).
It was a typical case in many TLS libraries that, for example, the second length variable has not been validated or processed, and thus its modification was meaningless.

Btw, we are currently working on TLS-Attacker 2. The information provided in the paper is not necessarily relevant for the current version.

**Comment by Krace** [comment]
thank you for your reply :P
