### ISSUE TITLE
Unable to compile without issues (Failed to execute goal "maven-surefire-plugin")

### ISSUE THREAD

**Issue by NetBender** [RUB-NDS/TLS-Attacker#43]
Hi.
I have cloned the repository and tried to compile using the `./mvnw clean package` command but, after an initial failure, i tried with the suggested `./mvnw -e clean package` to have more details.
The output [output](https://github.com/RUB-NDS/TLS-Attacker/files/2371758/log.txt) shows a failed execution of `org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test`.

I am using the following set up
- Asus K550JK;
- Ubuntu 18.04.1 LTS;
- Java 8 (as recommended in [another issue](https://github.com/RUB-NDS/TLS-Attacker/issues/40#issuecomment-381898808)).

I am not practical with Maven so i hope somebody can help me with this.
Thanks in advance.

**Comment by ic0ns** [comment]
Hm, we did not have this error before, but it seems unrelated to tls-attacker. Can you try running it without the maven wrapper but instead with maven directly?
eg:
```
sudo apt-get install maven
mvn clean install
```

**Comment by NetBender** [comment]
It worked flawlessly, thanks for your help.
