### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by mikeybro** [RUB-NDS/TLS-Attacker#46]
I was able to set this up on a Ubuntu server VM, but now I am wondering how to use the tool in general, would I be using this to test local servers? I don't know how to do that just yet, I have been learning about the PKI and cryptography but I still have alot more to learn and this repo looks like it can help learn, along with Java I am looking at the Code structure, I have experience with C, C++.

**Comment by ic0ns** [comment]
Hey mikeybro,
you can use this framework to test local or remote servers as you please (and have permission to).

**Comment by mikeybro** [comment]
Right that’s what I was thinking. So I would have to set up a server   Sounds fun I’ll be trying to do that. Right now  I’m still learning a lot  and was looking into protocols and pen testing. But it sounds like if I really wanted to use the tool I would have to learn some more things    I have nothing but time lol but I have seen all the resources and papers regarding the types of attacks and vulnerabilities. I was also wondering how this could help with penetrating and bug bounty programs

**Comment by ic0ns** [comment]
Good Luck with that! :100: :+1:
