### ISSUE TITLE
PaddingExtensionParser - The Padding Extension length value exceeds the two bytes defined in RFC 7685.

### ISSUE THREAD

**Issue by saravananmk** [RUB-NDS/TLS-Attacker#48]
When I run a  server like this:

java -jar TLS-Server.jar -port 44330

and try to connect to it using curl like this:

curl -k https://localhost:44330 --tlsv1.2 

It is giving a Warning:

15:07:12 [main] WARN : PaddingExtensionParser - The Padding Extension length value exceeds the two bytes defined in RFC 7685.

However, if I use TLSv1.0 or TLSv1.1, I do not see this warning.

The curl version I am using (from Ubuntu):

$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

Is that warning mean openssl has a bug (not RFC 7685 compliant)? Because the curl I am using is using openssl.

**Comment by ic0ns** [comment]
Thanks for reporting, this is not a bug in openssl , this is again a bug in TLS-Attacker. The Student who implemented the extension confused >= and <=  
```        
if (msg.getExtensionLength().getValue() <= 65535) {
    LOGGER.warn("The Padding Extension length value exceeds the two bytes defined in RFC 7685.");
}
```
should be 
```
if (msg.getExtensionLength().getValue() >= 65535) {
    LOGGER.warn("The Padding Extension length value exceeds the two bytes defined in RFC 7685.");
}
```
However the warning i still not useful since we cannot parse more bytes than 65535 here. Thanks for the report, i will fix this in the next version!

**Comment by saravananmk** [comment]
Thanks for the clarifications.

**Comment by ic0ns** [comment]
I fixed this in the dev version. It will be available in the next release
