### ISSUE TITLE
Some Small Adaptations

### ISSUE THREAD

**Issue by SidolFreiburg** [RUB-NDS/TLS-Attacker#49]
Hello!

We've done a lot of testing using the TLS Attacker and made some minor adjustments that might be of interest:

In TLS ProtocolVersion V1.1, the SignatureAndHash field is not supported in the messages CertificateRequest and CertificateVerify. We have added a conditional statement to the handler, parser and serialiser of the messages in question, e.g.:

```java
private void parseSignatureHashAlgorithmsLength(CertificateRequestMessage msg) {
    if(!ProtocolVersion.TLS11.equals(getVersion()) {
        msg.setSignatureHashAlgorithmsLength(parseIntField(HandshakeByteLength.SIGNATURE_HASH_ALGORITHMS_LENGTH));
        LOGGER.debug("SignatureHashAlgorithmsLength: " + msg.getSignatureHashAlgorithmsLength().getValue());
    }
}
```

According to the RFC, the client shall answer with an empty CertificateMessage to a CertificateRequest, if the the client is not able to provide a matching certificate. We were not sure how to to adjust the configuration and we added 
```java
       } else if (cert != null && !cert.isEmpty()) {
```
to 
https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/handler/CertificateMessageHandler.java#L92

We added 
```java
    ECDSA_SIGN((byte) 64),
```

to 
https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/constants/ClientCertificateType.java#L27

and we added brainpoolP256r1 and brainpoolP384r1

to 

https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/constants/NamedGroup.java#L218

Best regards
Matthias

**Comment by SidolFreiburg** [comment]
Excellent! Thanks a lot!

**Comment by SidolFreiburg** [comment]
We found further points that might be of interest: 

In
https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/certificate/CertificateKeyPair.java#L232
we added 
```
case "1.2.840.10045.4.3.4":
```
for ECDSA.

Also in 
https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/certificate/CertificateKeyPair.java#L355
we changed
```
context.setSelectedGroup(publicKeyGroup);
```
to
```
context.setEcCertificateCurve( publicKeyGroup );
```
Otherwise the curves that was selected for ecdhe during the handshake and the certificate's curve seem to get confused.

In
https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/crypto/keys/CustomECPrivateKey.java#L88
and also in line 92 we removed the
 ```
context.setSelectedGroup(group);
```
statement. This also seems to lead to a confusion between the curves from the Certificate and from the key exchange. The points mentioned above seem only relevant during client authentication.

For the next point, we are not sure about the intended behaviour: In
https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/handler/extension/EllipticCurvesExtensionHandler.java#L61
the supported curves are updated in the context regardless of which curves were chosen in the config. In our case, that resulted in the usage of a curve that was not meant to be used in the test-case.

Best regards
Matthias

**Comment by ic0ns** [comment]
Thanks for the additional feedback. As you might have guessed i did not play alot with client authentication yet. Some of your changes revealed even more flaws in the current code, especially in the certificate and group selection (as you already might have discovered). I will try to find a student to clean up the current code and write some unit tests. I changed the easy flaws in the CertificateRequest/Verify messages for <TLS1.2 and added the missing constants (also to the keypair).  We have bigger changes to the certificate handling in general upcoming. I'll keep you updated on the state of this issue.

**Comment by SidolFreiburg** [comment]
Hello! Thank you very much! I'll try out the new version soon. Meanwhile, we found some improvements for the STARTTLS implementation. What's the best way to communicate such changes? Should I post them here textually or would it be easier for you if I tried to attach some sort of diff files?

**Comment by ic0ns** [comment]
Hey,
if you dont mind you can just issue a pullrequest. Even if your code is not totally production ready. Otherwise, both diff files or textually would work aswell.

**Comment by SidolFreiburg** [comment]
Hello!
I recently made a quick check of the Version 2.8. I added the check for the ProtocolVersion here: https://github.com/RUB-NDS/TLS-Attacker/blob/626a7eea1ac8a047bd1fa9e8cfa686f104d3980c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/handler/CertificateRequestHandler.java#L55  Other than that, it seems to work. So from my point of view, if this line is fixed, you can close this issue.

Thank you for the note that it is possible to perform a pull request. I was not aware of that. For future findings I will use this means to notify you, since in most cases I had to fix them already in order to perform some tests.

Best regards
Matthias
