### ISSUE TITLE
how to deploy this project on myeclipse?

### ISSUE THREAD

**Issue by UCASREN** [RUB-NDS/TLS-Attacker#5]
I use IDE  myeclipse2015, I want to use this project to test some attacks on some Alex sites(e.g google.com, baidu.com....), so please tell me how to deploy it on myeclipse and test these  popular websites with attacks?
Very thx!!!!!

**Comment by jurajsomorovsky** [comment]
I am not familiar with myeclipse. Maybe this pull request will help you (?)
https://github.com/RUB-NDS/TLS-Attacker/pull/3

Please note that TLS-Attacker is not meant for testing real web servers, since the attacks are very aggressive and could harm servers.
