### ISSUE TITLE
Test failure in 3.0

### ISSUE THREAD

**Issue by randombit** [RUB-NDS/TLS-Attacker#59]
Following test fails for me

```
[ERROR] Failures: 
[ERROR]   ClientDelegateTest.bulkTest:153->checkHostIsAsExpected:189 
Expected: "localhost"
     but: was "localhost.localdomain"
[INFO] 
[ERROR] Tests run: 1723, Failures: 1, Errors: 0, Skipped: 5
```

```
$ grep localhost /etc/hosts
127.0.0.1	localhost.localdomain	localhost
```

I'm not sure how common localhost.localdomain is but that is the default value on Arch Linux.

I think the test just needs to be a bit less specific, perhaps requiring the name start with "localhost" but not be an exact match, or accepting "localhost.localdomain" as alternative.

**Comment by ic0ns** [comment]
ups, good catch. You are right. I will fix it tomorrow

**Comment by ic0ns** [comment]
It should now be fixed in the master branch.
