### ISSUE TITLE
Need some help 

### ISSUE THREAD

**Issue by FaheemBhatti** [RUB-NDS/TLS-Attacker#64]
Hi, i am using TLS-Attacker via importing libraries into my Java project, and upon using default handshake with the code below i am always getting :
Received Message( client): FATAL,DECODE_ERROR) 
I have created certificate authority via openssl and a client certificate which is signed by own created Root Certificate which is all good and working upon openssl handshake command.
please let me know if there is anything i have to add in my code or maybe any thing i am missing
Thank you
 
![Capture](https://user-images.githubusercontent.com/50632975/69322308-e9520f00-0c44-11ea-9fed-c6a8fba894e7.JPG)

**Comment by ic0ns** [comment]
The Problem ist that you are sending an RSA ClientKeyExchange message in an ECDHE Handshake. TLS-Attacker is very strict and does exactly what you configure it to do. Per default it has configured an RSA handshake, but proposes more than RSA ciphersuites in its ClientHello. If you want the Handshake to succeed you either have to change the client proposed ciphersuites in the config, adjust the defaultSelectedCipherSuite (in the config) or use a Dynamic WorkflowTraceType.
Cheers
Robert

**Comment by FaheemBhatti** [comment]
Thank you so much for the quick response, i'll update with both solutions :)

**Comment by FaheemBhatti** [comment]
![image](https://user-images.githubusercontent.com/50632975/69327110-42be3c00-0c4d-11ea-908e-a856a16470a0.png)


Thank you so much for guiding, it is working now,
Can you please guide me for writing test suits to run with this tool because i am new to TLS-Attacker and want to use this tool for testing openssl vulnerabilities. 
Thank you

**Comment by ic0ns** [comment]
I am not sure what information you are missing. Maybe a good point to start is to check that your workflowTraces executed (or not) the way you intended with trace.executedAsPlanned(); .
Other than that you can define workflows, send them to openssl and check that openssl reacts correctly. A helpful class for this is probably the WorkflowTraceUtil.java.
You can look for examples in the Attacks module.

**Comment by FaheemBhatti** [comment]
Thank you so much for guiding.
and i must say TLS-Attacker is a best tool so far :) 

Thank you,
Regards.
