### ISSUE TITLE
TlsContext couldn't get ServerCertificate

### ISSUE THREAD

**Issue by FaheemBhatti** [RUB-NDS/TLS-Attacker#67]
Hello Sir ,
As from your previous guidance, you told to fetch the server certificate from TlsContex.getServerCertificate(), but unfortunately it is returning a null value and upon reading TLsContext description it is mentioned that it sets the values on run time. 
Please let me know if there is something missing on my end to add for fetching the certificate.
And i also want to put my certificate as client certificate in TLS-Attacker. I have seen some certificates which are default certificates for TLS-Attacker but i want to put an external certificate in TLS-Attacker and want to configure it as client certificate. 
Thank you
![image](https://user-images.githubusercontent.com/50632975/70326607-41883400-1835-11ea-888e-1ab66b357930.png)

**Comment by ic0ns** [comment]
You are not using the context you executed the WorkflowTrace on. You want state2.getTlsContext(); For client certificates see your previous issue.

**Comment by FaheemBhatti** [comment]
Thank you
