### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by raffaellarobles** [RUB-NDS/TLS-Attacker#68]
Good morning, I'm an italian student and i want to know a bit more about this tool. Could you help me? Thanks in advance. Best regards.

**Comment by ic0ns** [comment]
Hey, i recommend reading the readme & wiki. If you have specific questions ask along... If you need code examples checkout the attacks module or the TLS-Scanner project (https://github.com/RUB-NDS/TLS-Scanner

**Comment by ic0ns** [comment]
And there is this: https://web-in-security.blogspot.com/2019/03/playing-with-tls-attacker.html?m=1

**Comment by raffaellarobles** [comment]
I have to write some workflow as xml files to test OpenSSL implementation
(with modified variables or fuzzing), do you have some examples of these
xml files ?
I can't program in Java. Thanks in advance


Il giorno gio 12 dic 2019 alle ore 12:46 Robert Merget <
notifications@github.com> ha scritto:

**Comment by raffaellarobles** [comment]
I've read it and i've understood how it works, but I would like to have a
practical example that shows OpenSSL bugs.


Il giorno gio 12 dic 2019 alle ore 12:55 Robert Merget <
notifications@github.com> ha scritto:

**Comment by raffaellarobles** [comment]
Of course if it's possible

Il giorno gio 12 dic 2019 alle ore 12:59 Raffaella Robles <
raffaella.robles.96@gmail.com> ha scritto:

**Comment by ic0ns** [comment]
Which bugs?

**Comment by raffaellarobles** [comment]
I have to test this TLS implementation so I want some Workflow's practical
example that performs fuzzing for example!

Il giorno gio 12 dic 2019 alle ore 13:24 Robert Merget <
notifications@github.com> ha scritto:

**Comment by ic0ns** [comment]
See https://github.com/RUB-NDS/TLS-Attacker/issues/58
