### ISSUE TITLE
how to test the specified URL with the TLS-Attacker?

### ISSUE THREAD

**Issue by UCASREN** [RUB-NDS/TLS-Attacker#7]
when I want to test  "https://www.youtube.com", I use this command:
`client -connect www.youtube.com:80 -cipher TLS_RSA_WITH_AES_256_CBC_SHA -version TLS12`

but I got followed errors:
`20:37:01.792 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Using the following security providers
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SUN, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunRsaSign, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunEC, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJSSE, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJCE, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunJGSS, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunSASL, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider XMLDSig, version, 1.0
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunPCSC, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider SunMSCAPI, version, 1.7
20:37:01.796 [main] DEBUG de.rub.nds.tlsattacker.tls.config.ConfigHandler - Provider BC, version, 1.54
20:37:02.323 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - Preparing the following protocol message to send: class de.rub.nds.tlsattacker.tls.protocol.handshake.ClientHelloMessage
20:37:02.328 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - 
CLIENT_HELLO
  Handshake Message Length: 99
  Protocol Version: TLS12
  Client Unix Time: Sat Jun 11 20:37:02 CST 2016
  Client Random: 
  BF DB 3E EC 68 43 CD B4  46 03 81 49 E6 93 BD 78 
  0C C7 10 60 0F D6 F5 91  0B FA 69 BA 
  Session ID: 
  Supported Cipher Suites: 00 35 
  Supported Compression Methods: 00 
  Extensions: 
20:37:02.329 [main] DEBUG de.rub.nds.tlsattacker.tls.record.RecordHandler - The protocol message(s) was split into 1 record(s).
20:37:02.334 [main] DEBUG de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor - Records going to be sent: 
  16 03 03 00 67 01 00 00  63 03 03 57 5C 05 EE BF 
  DB 3E EC 68 43 CD B4 46  03 81 49 E6 93 BD 78 0C 
  C7 10 60 0F D6 F5 91 0B  FA 69 BA 00 00 02 00 35 
  01 00 00 38 00 0A 00 0A  00 08 00 13 00 17 00 18 
  00 19 00 0B 00 02 01 00  00 0D 00 20 00 1E 06 01 
  06 02 06 03 05 01 05 02  05 03 04 01 04 02 04 03 
  03 01 03 02 03 03 02 01  02 02 02 03 
20:37:02.741 [main] DEBUG de.rub.nds.tlsattacker.transport.SimpleTransportHandler - Accepted 179 new bytes from server
20:37:02.741 [main] INFO  de.rub.nds.tlsattacker.Main - Could not identify valid protocol message type for the current record. The value in the record was: 72
de.rub.nds.tlsattacker.tls.exceptions.WorkflowExecutionException: Could not identify valid protocol message type for the current record. The value in the record was: 72
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.executeWorkflow(GenericWorkflowExecutor.java:86) ~[classes/:?]
	at de.rub.nds.tlsattacker.Main.startSimpleTls(Main.java:197) [classes/:?]
	at de.rub.nds.tlsattacker.Main.main(Main.java:124) [classes/:?]
Caused by: de.rub.nds.tlsattacker.tls.exceptions.WorkflowExecutionException: Could not identify valid protocol message type for the current record. The value in the record was: 72
	at de.rub.nds.tlsattacker.tls.record.RecordHandler.parseRecords(RecordHandler.java:161) ~[classes/:?]
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.fetchRecords(GenericWorkflowExecutor.java:289) ~[classes/:?]
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.handleProtocolMessagesFromPeer(GenericWorkflowExecutor.java:152) ~[classes/:?]
	at de.rub.nds.tlsattacker.tls.workflow.GenericWorkflowExecutor.executeWorkflow(GenericWorkflowExecutor.java:82) ~[classes/:?]
	... 2 more
20:37:02.747 [main] CONSOLE de.rub.nds.tlsattacker.Main - The TLS protocol flow was not executed completely, follow the debug messages for more information.
`

I just want to use the TLS-Attacker to test some real urls, how should I write the command, or alter the source code. I am in a hurry,  very thx!!!

other problems:
    How to write the xml file, can you explain in detail?

**Comment by jurajsomorovsky** [comment]
As mentioned in the TLS-Attacker documentation, this tool is meant to test TLS libraries. You can use it to test real websites as well, but you should be aware of what you are doing. For this, I encourage you to read something about TLS (e.g., https://en.wikipedia.org/wiki/Transport_Layer_Security, where you can find out that TLS works on port 443, and not 80) and then test some servers locally (e.g. OpenSSL).

Regarding the XML workflows, please take a look into the TLS-Attacker wiki. You can also find many examples here: https://github.com/RUB-NDS/TLS-Attacker/tree/master/resources/fuzzing/workflows
