### ISSUE TITLE
What is the modifiable value expression to be used for sending level in "Alert messages"

### ISSUE THREAD

**Issue by sajualways** [RUB-NDS/TLS-Attacker#77]
I have used below one but it failed to execute

08:02:25 [main] ERROR: TlsClient - Encountered an uncaught Exception aborting. See debug for more info.
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte

Is this modifiable value correct for Alert level ?
"integerExplicitValueModification"

<Send>
        <messages>
            <Alert>
                <level>
                        <integerExplicitValueModification>
                                <explicitValue>01</explicitValue>
                        </integerExplicitValueModification>
                </level>
            </Alert>
        </messages>
    </Send>

**Comment by ic0ns** [comment]
```
    <byteExplicitValueModification>
        <explicitValue>
            01
        </explicitValue>
    </byteExplicitValueModification>
```

**Comment by sajualways** [comment]
Now it is working but why is this null value in the log->i have not put any description->by default it is taking Close notify as Description while sending

08:11:26 [main] INFO : SendAction - Sending messages (client): Alert(WARNING,null), 
08:11:26 [main] INFO : ReceiveAction - Received Messages (client): Alert(WARNING,CLOSE_NOTIFY),

**Comment by ic0ns** [comment]
are you trying to send an undefined description?

**Comment by sajualways** [comment]
actually i did not send any alert description....but it was sending "Close notify as description" and later i explicitly sent the description and it worked
