### ISSUE TITLE
Allow for external Socket to be provided

### ISSUE THREAD

**Issue by BenBE** [RUB-NDS/TLS-Attacker#8]
When testing SSL libraries and services it would be nice to have a way of providing an already initialized connection to the test flow so that things like STARTTLS on various protocols (SMTP, POP3, IMAP, MySQL, PostgreSQL, HTTP Upgrade, XMPP, ... come to mind) can be tested. Doing so allows to check the interaction in real services that implement their SSL through an upgrade mechanisms or have security only as an optional feature.

If there's already something that can be used to achieve this I'd be glad for some pointers.

**Comment by jurajsomorovsky** [comment]
No, this is not yet implemented and has not been considered yet. I considered adding STARTTLS connection support, but your idea would be even more general and probably better. 

Do you have any idea how this can be implemented? ...e.g. specific projects using such a mechanism?

**Comment by jurajsomorovsky** [comment]
Maybe creating a socket using a proxy?
https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#Socket(java.net.Proxy)

The proxy should then take care of STARTTLS etc. ?

**Comment by BenBE** [comment]
The interface that most likely should fit your current structure would be building a small interface to receive notifications for several events related to the socket / connection lifetime, which can be set in the CommandConfiguration. A sample interface might look like:

```java
interface ConnectionListener {
    Socket getSocket(...); //Initialize the socket / e.g. set special TCP flags
    bool beforeConnect(...); //Prepare things before connecting (e.g. check IPs, precompute things, ...)
    bool afterConnect(...); //Connection just established; maybe send early data (e.g. STARTTLS)
    bool beforeFlow(...); //Just starting to send packets of the flow for this connection
    bool receivedFrame(...); //Once for each received frame; e.g. to cancel early
    bool sentFrame(...); //Once before sending each frame; e.g. to suppress frames in certain situations
    bool afterFlow(...); //The prepared flow was completed
    bool beforeDisconnect(...); //Nothing left to do
    bool afterDisconnect(...); //Just after the connection was closed
    // Maybe others
}
```

Maybe splitting of this interface is possible/sensible. For STARTTLS you could either use afterConnect or beforeFlow to prepare the connection as needed.

**Comment by drwetter** [comment]
Hi Juraj,

Am 07/10/2016 um 07:48 PM schrieb Juraj Somorovsky:
> No, this is not yet implemented and has not been considered yet. I considered adding STARTTLS
> connection support, but your idea would be even more general and probably better.
> 
> Do you have any idea how this can be implemented? ...e.g. specific projects using such a mechanism?

here! :-)

@BenBE suggested the right thing IMO.


You might as well have a look @ fd_socket() in
https://github.com/drwetter/testssl.sh/blob/master/testssl.sh#L4773

It's not that hard...


Cheers, Dirk

**Comment by jurajsomorovsky** [comment]
Thank you for the input @BenBE and @drwetter . I have to reconsider your suggestions ...and find some free time to implement this :)

**Comment by ic0ns** [comment]
fixed in our internal repo, will be released in the next version
