### ISSUE TITLE
Does not implement NULL Key Exchange

### ISSUE THREAD

**Issue by BenBE** [RUB-NDS/TLS-Attacker#9]
When trying to execute a handshake offering each and every cipher suite available initialization of the TLS Conext fails.

Steps to reproduce:
```java
    public static void main(String[] args) {
        // v--- Get all available ciphers.
        ArrayList<CipherSuite> ciphers = new ArrayList<CipherSuite>(Arrays.asList(CipherSuite.values()));

        GeneralConfig generalConfig = new GeneralConfig();
        generalConfig.setQuiet(false);
        generalConfig.setDebug(true);

        HeartbleedCommandConfig heartbleed = new HeartbleedCommandConfig();
        heartbleed.setConnect("some.domain.tld:443");
        heartbleed.setProtocolVersion(ProtocolVersion.TLS12);
        heartbleed.setCipherSuites(ciphers); // <--- Set all ciphers here

        Attacker<ClientCommandConfig> attacker = new Attacker<ClientCommandConfig>(heartbleed) {

            @Override
            public void executeAttack(ConfigHandler configHandler) {
                // Skipped for brevity ...
            }

        };

        ConfigHandler configHandler = ConfigHandlerFactory.createConfigHandler(ClientCommandConfig.COMMAND);
        configHandler.initialize(generalConfig);

        attacker.executeAttack(configHandler);
    }
```

Expected result:
A TLS context is created and the configured handshake sent to the server

Actual result:
```
Exception in thread "main" java.lang.UnsupportedOperationException: The key exchange algorithm is not supported yet.
	at de.rub.nds.tlsattacker.tls.constants.AlgorithmResolver.getKeyExchangeAlgorithm(AlgorithmResolver.java:97)
	at de.rub.nds.tlsattacker.tls.workflow.WorkflowConfigurationFactory.createInstance(WorkflowConfigurationFactory.java:54)
	at de.rub.nds.tlsattacker.tls.config.ClientConfigHandler.initializeTlsContext(ClientConfigHandler.java:62)
	at tld.domain.ssltest.TLSAttackerClient$1.executeAttack(TLSAttackerClient.java:47)
	at tld.domain.ssltest.TLSAttackerClient.main(TLSAttackerClient.java:93)
```

The cipher it is complaining about is TLS_NULL_WITH_NULL_NULL.
Although prohibited by RFC it shouldn't crash in context creation ;-)

I guess other Kex like PSK, SRP and KRB5 are affected as well.

**Comment by jurajsomorovsky** [comment]
TLS-Attacker per default takes the first cipher suite from the configuration list and creates a workflow based on this cipher suite. You can use `CipherSuite.getImplemented` method to get a list of all implemented cipher suites.

However, dynamic TLS workflows are not supported yet, so you will also run into problems if the first cipher suite in the list is RSA-based, but the server chooses  ECDHE-RSA. 
This is something I have to work on, but until now it was not needed for our tests...

**Comment by BenBE** [comment]
I stumbled upon this issue when porting over a testcase to detect all server-supported ciphers.

Current working draft @ https://github.com/BenBE/ssltest/blob/master/src/de/dogcraft/ssltest/TLSAttackerClient.java - The order there needs to be from worst to best, in order to detect server preference over client preference of cipher suite order (off-topic here).

For the dynamic workflow a base class DynamicWorkflow with a "ProtocolMessage[] generateNextMessage(Ctx)" might be an idea, where the return gives a list of expected replies. If it contains any Client-originated message, those are sent (in array order), if at least one Server-originated message is listed, the next Record from the server is fetched (and checked to match to ANY of the server messages).

But back to the actual issue of this report: If the Workflow does not support a certain key exchange type the easiest solution would be to only create a stub handshake containing ClientHello and ServerHello. If a full handshake with an unsuppoerted Kex is required, a dynamic workflow (see paragraph above) should be used instead.

How does this sound?

**Comment by jurajsomorovsky** [comment]
Thanks, I implemented it according to your proposition. All key exchanges should now be working and in case they are not supported, the client just sends a client hello messages and waits for an arbitrary message from the server.

The dynamic workflow however takes some time and will be implemented later.

Could you re-check please?

**Comment by BenBE** [comment]
Sure, I'll recheck; might take a few days though.

**Comment by BenBE** [comment]
Issue looks closed; CNR with latest commit (on my branch rebased on your master).

Will open a follow up issue for the Curve25519 issue I get now (play.google.com causes crash in ServerKeyExchange parsing) - details follow including pcap and log.
